In [2]:
import pandas as pd
import numpy as np

In [3]:
customers = pd.read_csv("datasets/customers.csv")

orders = pd.read_csv("datasets/orders.csv")

order_items = pd.read_csv("datasets/order_items.csv")

payments = pd.read_csv("datasets/payments.csv")

products = pd.read_csv("datasets/products.csv")

reviews = pd.read_csv("datasets/reviews.csv")

sellers = pd.read_csv("datasets/sellers.csv")

geolocation = pd.read_csv("datasets/geolocation.csv")

### check shapes

In [4]:
print("Customers Shape:", customers.shape)

print("Orders Shape:", orders.shape)

print("Order Items Shape:", order_items.shape)

print("Payments Shape:", payments.shape)

print("Products Shape:", products.shape)

print("Reviews Shape:", reviews.shape)

print("Sellers Shape:", sellers.shape)

print("Geolocation Shape:", geolocation.shape)

Customers Shape: (10300, 8)
Orders Shape: (30600, 8)
Order Items Shape: (92576, 7)
Payments Shape: (37407, 5)
Products Shape: (5100, 9)
Reviews Shape: (31212, 7)
Sellers Shape: (515, 4)
Geolocation Shape: (10300, 5)

### view first 5 rows

In [5]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code,customer_city,customer_state,signup_date,gender,age
0,CUST00001,UNQ00001,258183.0,Phagwara,Maharashtra,2024-11-10,female,-5
1,CUST00002,UNQ00002,866415.0,North Dumdum,West Bengal,2024-05-20,FEMALE,53
2,CUST00003,UNQ00003,299501.0,Amaravati,Odisha,2026-05-18,MALE,23
3,CUST00004,UNQ00004,770654.0,GORAKHPUR,West Bengal,2025-09-16,FEMALE,57
4,CUST00005,UNQ00005,521728.0,Buxar,Bihar,2024-09-22,Male,48

In [6]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,ORD000001,CUST03146,cancelled,2026-01-02 08:56:14,2026-01-02 11:25:14,NaN,NaN,2026-01-12 08:56:14
1,ORD000002,CUST03000,shipped,2026-04-08 04:47:38,2026-04-08 13:31:38,2026-04-10 13:31:38,2026-04-18 13:31:38,2026-04-19 13:31:38
2,ORD000003,CUST05641,delivered,2024-09-05 19:06:02,2024-09-06 00:53:02,2024-09-07 00:53:02,2024-09-16 00:53:02,2024-09-21 00:53:02
3,ORD000004,CUST07018,delivered,2025-07-05 15:15:31,2025-07-05 23:36:31,2025-07-06 23:36:31,2025-07-12 23:36:31,2025-07-16 23:36:31
4,ORD000005,CUST07070,delivered,2025-12-30 11:28:37,2025-12-30 13:40:37,2025-12-31 13:40:37,2026-01-03 13:40:37,2026-01-05 13:40:37

In [7]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,ORD000001,1,PROD03340,SELL0319,2026-01-04 08:56:14,4370.90,309.90
1,ORD000001,2,PROD04013,SELL0167,2026-01-05 08:56:14,161.25,20.48
2,ORD000001,3,PROD01532,SELL0384,2026-01-08 08:56:14,2135.03,224.74
3,ORD000001,4,PROD04212,SELL0299,2026-01-07 08:56:14,3747.98,481.04
4,ORD000002,1,PROD03394,SELL0045,2026-04-09 04:47:38,910.00,73.19

In [8]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,ORD000001,1,debit_card,1,173.41
1,ORD000002,1,net_banking,1,2330.31
2,ORD000002,2,net_banking,1,1223.90
3,ORD000003,1,net_banking,1,1183.51
4,ORD000004,1,NaN,1,8095.70

In [9]:
products.head()

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,PROD00001,fashion,57,1772,7,5088.91,56.00,4.71,32.20
1,PROD00002,home_decor,75,1944,2,7464.63,55.79,48.93,75.96
2,PROD00003,pet_supplies,24,1829,4,5749.25,27.38,34.04,43.17
3,PROD00004,kitchen,48,1404,6,3417.74,5.79,50.34,11.21
4,PROD00005,fashion,13,1350,1,1642.05,24.13,20.10,NaN

In [10]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,REV556851,ORD000001,5,Fast Delivery,Received the product on time.,2026-01-17 08:56:14,2026-01-17 23:56:14
1,REV737442,ORD000002,4,Very Good,Very satisfied with the purchase.,2026-04-14 04:47:38,2026-04-14 08:47:38
2,REV372250,ORD000003,3,Highly Recommended,Average product but acceptable.,2024-09-24 19:06:02,2024-09-26 17:06:02
3,REV996442,ORD000004,2,Not Bad,Very satisfied with the purchase.,2025-07-15 15:15:31,2025-07-18 03:15:31
4,REV736982,ORD000005,1,Poor Packaging,Packaging could have been better.,2026-01-17 11:28:37,2026-01-20 11:28:37

In [11]:
sellers.head()

  seller_id  seller_zip_code seller_city   seller_state
0  SELL0001         784939.0       KORBA       Nagaland
1  SELL0002         276425.0      bhopal            Goa
2  SELL0003         918444.0     Nashik         Mizoram
3  SELL0004         376335.0    jamnagar  Uttar Pradesh
4  SELL0005         247862.0      Bhilai        Gujarat

In [12]:
geolocation.head()

,geolocation_zip_code,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,474583,8.727583,83.291202,Jamnagar,Bihar
1,549522,33.089109,82.278672,raichur,Odisha
2,202045,15.611905,83.404144,Srinagar,Chhattisgarh
3,401102,20.598928,71.861622,Ludhiana,Uttar Pradesh
4,922422,11.551207,96.618818,Mehsana,Manipur

In [13]:
customers.head()

orders.head()

order_items.head()

payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,ORD000001,1,debit_card,1,173.41
1,ORD000002,1,net_banking,1,2330.31
2,ORD000002,2,net_banking,1,1223.90
3,ORD000003,1,net_banking,1,1183.51
4,ORD000004,1,NaN,1,8095.70

### check column info

In [14]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         10300 non-null  str
 1   customer_unique_id  10300 non-null  str
 2   customer_zip_code   9994 non-null   float64
 3   customer_city       9796 non-null   str
 4   customer_state      10300 non-null  str
 5   signup_date         10002 non-null  str
 6   gender              10300 non-null  str
 7   age                 10300 non-null  int64
dtypes: float64(1), int64(1), str(6)
memory usage: 643.9 KB

In [15]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 30600 entries, 0 to 30599
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       30600 non-null  str
 1   customer_id                    30600 non-null  str
 2   order_status                   30600 non-null  str
 3   order_purchase_timestamp       30600 non-null  str
 4   order_approved_at              30600 non-null  str
 5   order_delivered_carrier_date   28393 non-null  str
 6   order_delivered_customer_date  28393 non-null  str
 7   order_estimated_delivery_date  30600 non-null  str
dtypes: str(8)
memory usage: 1.9 MB

In [16]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 92576 entries, 0 to 92575
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             92576 non-null  str
 1   order_item_id        92576 non-null  int64
 2   product_id           92576 non-null  str
 3   seller_id            92576 non-null  str
 4   shipping_limit_date  92576 non-null  str
 5   price                89826 non-null  float64
 6   freight_value        92576 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 4.9 MB

In [17]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 37407 entries, 0 to 37406
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              37407 non-null  str
 1   payment_sequential    37407 non-null  int64
 2   payment_type          35941 non-null  str
 3   payment_installments  37407 non-null  int64
 4   payment_value         37407 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 1.4 MB

In [18]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  5100 non-null   str
 1   product_category_name       4991 non-null   str
 2   product_name_length         5100 non-null   int64
 3   product_description_length  5100 non-null   int64
 4   product_photos_qty          5100 non-null   int64
 5   product_weight_g            5100 non-null   float64
 6   product_length_cm           5002 non-null   float64
 7   product_height_cm           5025 non-null   float64
 8   product_width_cm            4994 non-null   float64
dtypes: float64(4), int64(3), str(2)
memory usage: 358.7 KB

In [19]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 31212 entries, 0 to 31211
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                31212 non-null  str
 1   order_id                 31212 non-null  str
 2   review_score             31212 non-null  int64
 3   review_comment_title     30587 non-null  str
 4   review_comment_message   29682 non-null  str
 5   review_creation_date     31212 non-null  str
 6   review_answer_timestamp  30280 non-null  str
dtypes: int64(1), str(6)
memory usage: 1.7 MB

In [20]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   seller_id        515 non-null    str
 1   seller_zip_code  496 non-null    float64
 2   seller_city      500 non-null    str
 3   seller_state     515 non-null    str
dtypes: float64(1), str(3)
memory usage: 16.2 KB

In [21]:
geolocation.info()

<class 'pandas.DataFrame'>
RangeIndex: 10300 entries, 0 to 10299
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   geolocation_zip_code  10300 non-null  int64
 1   geolocation_lat       10259 non-null  float64
 2   geolocation_lng       10267 non-null  float64
 3   geolocation_city      9969 non-null   str
 4   geolocation_state     10300 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 402.5 KB

### check null values

In [22]:
print("Customers Null Values\n")
print(customers.isnull().sum())

print("\nOrders Null Values\n")
print(orders.isnull().sum())

print("\nOrder Items Null Values\n")
print(order_items.isnull().sum())

print("\nPayments Null Values\n")
print(payments.isnull().sum())

print("\nProducts Null Values\n")
print(products.isnull().sum())

print("\nReviews Null Values\n")
print(reviews.isnull().sum())

print("\nSellers Null Values\n")
print(sellers.isnull().sum())

print("\nGeolocation Null Values\n")
print(geolocation.isnull().sum())

Customers Null Values

customer_id             0
customer_unique_id      0
customer_zip_code     306
customer_city         504
customer_state          0
signup_date           298
gender                  0
age                     0
dtype: int64

Orders Null Values

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   0
order_delivered_carrier_date     2207
order_delivered_customer_date    2207
order_estimated_delivery_date       0
dtype: int64

Order Items Null Values

order_id                  0
order_item_id             0
product_id                0
seller_id                 0
shipping_limit_date       0
price                  2750
freight_value             0
dtype: int64

Payments Null Values

order_id                   0
payment_sequential         0
payment_type            1466
payment_installments       0
payment_value              0
dtype: int64

Products Null Values

product_id                      0
product_category_name         109
product_name_length             0
product_description_length      0
product_photos_qty              0
product_weight_g                0
product_length_cm              98
product_height_cm              75
product_width_cm              106
dtype: int64

Reviews Null Values

review_id                     0
order_id                      0
review_score                  0
review_comment_title        625
review_comment_message     1530
review_creation_date          0
review_answer_timestamp     932
dtype: int64

Sellers Null Values

seller_id           0
seller_zip_code    19
seller_city        15
seller_state        0
dtype: int64

Geolocation Null Values

geolocation_zip_code      0
geolocation_lat          41
geolocation_lng          33
geolocation_city        331
geolocation_state         0
dtype: int64

### handle null values

#### 1) Customers

In [23]:
customers["customer_zip_code"] = customers["customer_zip_code"].fillna(customers["customer_zip_code"].median())

In [24]:
customers["customer_city"] = customers["customer_city"].fillna("Unknown")

In [25]:
customers["signup_date"] = customers["signup_date"].fillna(customers["signup_date"].mode()[0])

#### 2) Orders

In [26]:
orders["order_delivered_carrier_date"] = orders["order_delivered_carrier_date"].fillna(orders["order_estimated_delivery_date"])

In [27]:
orders["order_delivered_customer_date"] = orders["order_delivered_customer_date"].fillna(orders["order_estimated_delivery_date"])

#### 3) Order items

In [28]:
order_items["price"] = order_items["price"].fillna(order_items["price"].median())

#### 4) Payments table

In [29]:
payments["payment_type"] = payments["payment_type"].fillna("unknown")

#### 5) Products table

In [30]:
products["product_category_name"] = products["product_category_name"].fillna("unknown")

In [31]:
products["product_length_cm"] = products["product_length_cm"].fillna(products["product_length_cm"].median())

In [32]:
products["product_height_cm"] = products["product_height_cm"].fillna(products["product_height_cm"].median())

In [33]:
products["product_width_cm"] = products["product_width_cm"].fillna(products["product_width_cm"].median())

#### 6) Reviews table

In [34]:
reviews["review_comment_title"] = reviews["review_comment_title"].fillna("No Title")

In [35]:
reviews["review_comment_message"] = reviews["review_comment_message"].fillna("No Comment")

In [36]:
reviews["review_answer_timestamp"] = reviews["review_answer_timestamp"].fillna(reviews["review_creation_date"])

#### 7) Sellers

In [37]:
sellers["seller_zip_code"] = sellers["seller_zip_code"].fillna(sellers["seller_zip_code"].median())

In [38]:
sellers["seller_city"] = sellers["seller_city"].fillna("Unknown")

#### 8) Geolocation table

In [39]:
geolocation["geolocation_lat"] = geolocation["geolocation_lat"].fillna(geolocation["geolocation_lat"].median())

In [40]:
geolocation["geolocation_lng"] = geolocation["geolocation_lng"].fillna(geolocation["geolocation_lng"].median())

In [41]:
geolocation["geolocation_city"] = geolocation["geolocation_city"].fillna("Unknown")

## check duplicates

In [42]:
print("Customers Duplicates:", customers.duplicated().sum())

print("Orders Duplicates:", orders.duplicated().sum())

print("Order Items Duplicates:", order_items.duplicated().sum())

print("Payments Duplicates:", payments.duplicated().sum())

print("Products Duplicates:", products.duplicated().sum())

print("Reviews Duplicates:", reviews.duplicated().sum())

print("Sellers Duplicates:", sellers.duplicated().sum())

print("Geolocation Duplicates:", geolocation.duplicated().sum())

Customers Duplicates: 300
Orders Duplicates: 600
Order Items Duplicates: 917
Payments Duplicates: 733
Products Duplicates: 100
Reviews Duplicates: 612
Sellers Duplicates: 15
Geolocation Duplicates: 300

## remove  duplicates

In [43]:
customers.drop_duplicates(inplace=True)

In [44]:
orders.drop_duplicates(inplace=True)

In [45]:
order_items.drop_duplicates(inplace=True)

In [46]:
payments.drop_duplicates(inplace=True)

In [47]:
products.drop_duplicates(inplace=True)

In [48]:
reviews.drop_duplicates(inplace=True)

In [49]:
sellers.drop_duplicates(inplace=True)

In [50]:
geolocation.drop_duplicates(inplace=True)

## remove extra spaces

#### 1) coustomers

In [51]:
customers["customer_city"] = customers["customer_city"].str.strip()

customers["customer_state"] = customers["customer_state"].str.strip()

customers["gender"] = customers["gender"].str.strip()

#### 2) orders

In [52]:
orders["order_status"] = orders["order_status"].str.strip()

#### 3) products

In [53]:
products["product_category_name"] = products["product_category_name"].str.strip()

#### 4) payments

In [54]:
payments["payment_type"] = payments["payment_type"].str.strip()

#### 5) sellers

In [55]:
sellers["seller_city"] = sellers["seller_city"].str.strip()

sellers["seller_state"] = sellers["seller_state"].str.strip()

#### 6) geolocation

In [56]:
geolocation["geolocation_city"] = geolocation["geolocation_city"].str.strip()

geolocation["geolocation_state"] = geolocation["geolocation_state"].str.strip()

## check data types

In [57]:
print("Customers Data Types\n")
print(customers.dtypes)

print("\nOrders Data Types\n")
print(orders.dtypes)

print("\nOrder Items Data Types\n")
print(order_items.dtypes)

print("\nPayments Data Types\n")
print(payments.dtypes)

print("\nProducts Data Types\n")
print(products.dtypes)

print("\nReviews Data Types\n")
print(reviews.dtypes)

print("\nSellers Data Types\n")
print(sellers.dtypes)

print("\nGeolocation Data Types\n")
print(geolocation.dtypes)

Customers Data Types

customer_id               str
customer_unique_id        str
customer_zip_code     float64
customer_city             str
customer_state            str
signup_date               str
gender                    str
age                     int64
dtype: object

Orders Data Types

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

Order Items Data Types

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

Payments Data Types

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Products Data Types

product_id                        str
product_category_name             str
product_name_length             int64
product_description_length      int64
product_photos_qty              int64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Reviews Data Types

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Sellers Data Types

seller_id              str
seller_zip_code    float64
seller_city            str
seller_state           str
dtype: object

Geolocation Data Types

geolocation_zip_code      int64
geolocation_lat         float64
geolocation_lng         float64
geolocation_city            str
geolocation_state           str
dtype: object

## convert date columns

#### Customers

In [58]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])

#### orders

In [59]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])

orders["order_approved_at"] = pd.to_datetime(orders["order_approved_at"])

orders["order_delivered_carrier_date"] = pd.to_datetime(orders["order_delivered_carrier_date"])

orders["order_delivered_customer_date"] = pd.to_datetime(orders["order_delivered_customer_date"])

orders["order_estimated_delivery_date"] = pd.to_datetime(orders["order_estimated_delivery_date"])

#### order items

In [60]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

#### reviews

In [61]:
reviews["review_creation_date"] = pd.to_datetime(reviews["review_creation_date"])

reviews["review_answer_timestamp"] = pd.to_datetime(reviews["review_answer_timestamp"])

## check outliers

In [62]:
customers.describe()

       customer_zip_code                 signup_date           age
count       10000.000000                       10000  10000.000000
mean       549621.397900  2024-11-05 13:53:54.240000     42.352200
min        100091.000000         2023-05-21 00:00:00     -5.000000
25%        331031.250000         2024-01-19 00:00:00     29.000000
50%        553580.000000         2024-11-03 12:00:00     42.000000
75%        764723.750000         2025-08-10 00:00:00     54.000000
max        999893.000000         2026-05-20 00:00:00    150.000000
std        255372.597236                         NaN     17.740277

In [63]:
orders.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,30000,30000,30000,30000,30000
mean,2025-05-21 21:32:43.067166,2025-05-22 03:35:15.023166,2025-05-24 11:14:08.295166,2025-05-30 00:02:48.615166,2025-06-01 07:52:17.895166
min,2024-05-21 10:47:15,2024-05-21 13:33:40,2024-05-22 20:03:43,2024-05-25 02:15:06,2024-05-25 03:48:36
25%,2024-11-21 20:42:12.250000,2024-11-22 02:48:03,2024-11-24 11:14:20,2024-11-29 21:21:56.250000,2024-12-02 08:03:52.500000
50%,2025-05-23 17:54:43.500000,2025-05-24 00:38:23,2025-05-26 09:15:05,2025-06-01 05:04:02.500000,2025-06-03 10:39:01
75%,2025-11-18 19:52:44,2025-11-19 02:37:20.750000,2025-11-21 08:42:12.250000,2025-11-27 02:03:48.500000,2025-11-29 05:51:42.500000
max,2026-05-21 20:26:55,2026-05-22 07:54:49,2026-05-31 04:21:56,2026-06-02 18:09:58,2026-06-06 18:09:58

In [64]:
order_items.describe()

       order_item_id         shipping_limit_date         price  freight_value
count   91659.000000                       91659  91659.000000   91659.000000
mean        2.332766  2025-05-25 19:55:57.199086   2553.036765     229.533952
min         1.000000         2024-05-22 11:39:22    100.140000       3.180000
25%         1.000000         2024-11-25 10:43:34   1353.540000      99.180000
50%         2.000000         2025-05-27 19:51:52   2546.285000     194.400000
75%         3.000000         2025-11-24 04:09:21   3762.440000     332.160000
max         5.000000         2026-05-28 20:26:55   4999.860000     747.940000
std         1.247526                         NaN   1400.657641     162.088695

In [65]:
payments.describe()

       payment_sequential  payment_installments  payment_value
count        36674.000000          36674.000000   36674.000000
mean             1.206850              2.051590    4176.758896
std              0.496514              2.699223    2929.172110
min              1.000000             -2.000000     -10.990000
25%              1.000000              1.000000    1554.350000
50%              1.000000              1.000000    3759.525000
75%              1.000000              1.000000    6599.225000
max              3.000000             12.000000    9999.800000

In [66]:
products.describe()

,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,44.831200,1028.693200,5.536000,11745.345028,51.934201,30.541128,42.212435
std,20.386432,564.373698,2.874362,81830.481631,26.741740,16.945818,21.271910
min,10.000000,50.000000,1.000000,-500.000000,5.010000,-10.000000,5.040000
25%,28.000000,539.750000,3.000000,2532.435000,28.710000,16.417500,24.417500
50%,45.000000,1033.000000,6.000000,4965.670000,51.925000,30.490000,41.805000
75%,62.000000,1516.500000,8.000000,7483.710000,74.700000,44.962500,60.432500
max,80.000000,2000.000000,10.000000,999999.000000,99.940000,59.980000,79.980000

In [67]:
reviews.describe()

       review_score        review_creation_date     review_answer_timestamp
count  30600.000000                       30600                       30600
mean       3.069608  2025-06-02 09:19:21.342189  2025-06-03 21:22:33.459836
min        1.000000         2024-05-24 12:44:49         2024-05-26 21:23:53
25%        2.000000  2024-12-03 06:14:44.250000  2024-12-04 18:25:08.750000
50%        3.000000         2025-06-04 04:32:43  2025-06-05 20:51:45.500000
75%        4.000000         2025-11-30 15:39:29  2025-12-01 21:39:02.500000
max       10.000000         2026-06-10 04:36:01         2026-06-12 00:08:46
std        1.578845                         NaN                         NaN

In [68]:
sellers.describe()

       seller_zip_code
count     5.000000e+02
mean      6.179317e+05
std       8.811019e+05
min      -1.000000e+02
25%       3.167725e+05
50%       5.588915e+05
75%       7.532038e+05
max       9.999999e+06

In [69]:
geolocation.describe()

       geolocation_zip_code  geolocation_lat  geolocation_lng
count          1.000000e+04     10000.000000     10000.000000
mean           6.065918e+05        20.437168        79.924591
std            8.218584e+05        54.813625        57.667672
min           -1.000000e+02      -999.000000      -999.000000
25%            3.168665e+05        15.228970        74.981419
50%            5.445845e+05        22.456284        82.355672
75%            7.820168e+05        29.670763        89.623052
max            9.999999e+06       200.000000       300.000000

## outlier handling

#### customers

In [70]:
customers = customers[
    (customers["age"] >= 18) &
    (customers["age"] <= 80)
]                                 # invalid ages

#### payments

In [71]:
payments = payments[
    payments["payment_installments"] >= 0
]                                             # negative installments

In [72]:
payments = payments[
    payments["payment_value"] >= 0
]                                            # negative payments values

#### products

In [73]:
products = products[
    (products["product_weight_g"] > 0) &
    (products["product_weight_g"] <= 50000)
]                                                 # Invalid Product Weights

In [74]:
products = products[
    products["product_height_cm"] > 0
]                                              # negative height

#### sellers

In [75]:
sellers = sellers[
    sellers["seller_zip_code"] > 0
]                                          # negative ZIP codes

#### geolocation

In [76]:
geolocation = geolocation[
    (geolocation["geolocation_lat"] >= -90) &
    (geolocation["geolocation_lat"] <= 90)
]                                                 # latitude outside valid Earth range

In [77]:
geolocation = geolocation[
    (geolocation["geolocation_lng"] >= -180) &
    (geolocation["geolocation_lng"] <= 180)
]                                                 # longitude outside valid Earth range

#### reviews

In [78]:
reviews = reviews[
    (reviews["review_score"] >= 1) &
    (reviews["review_score"] <= 5)
]                                         # scores above 5

## check final null values

In [79]:
print("Customers")
print(customers.isnull().sum())

print("\nOrders")
print(orders.isnull().sum())

print("\nOrder Items")
print(order_items.isnull().sum())

print("\nPayments")
print(payments.isnull().sum())

print("\nProducts")
print(products.isnull().sum())

print("\nReviews")
print(reviews.isnull().sum())

print("\nSellers")
print(sellers.isnull().sum())

print("\nGeolocation")
print(geolocation.isnull().sum())

Customers
customer_id           0
customer_unique_id    0
customer_zip_code     0
customer_city         0
customer_state        0
signup_date           0
gender                0
age                   0
dtype: int64

Orders
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Products
product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

Reviews
review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

Sellers
seller_id          0
seller_zip_code    0
seller_city        0
seller_state       0
dtype: int64

Geolocation
geolocation_zip_code    0
geolocation_lat         0
geolocation_lng         0
geolocation_city        0
geolocation_state       0
dtype: int64

## create cleaned data folder

In [80]:
import os
os.makedirs("cleaned_data", exist_ok=True)

## saving cleaned files

In [92]:
customers.to_excel("cleaned_data/customers_cleaned.xlsx",index=False)
orders.to_excel("cleaned_data/orders_cleaned.xlsx", index=False)
order_items.to_excel("cleaned_data/order_items_cleaned.xlsx", index=False)
payments.to_excel("cleaned_data/payments_cleaned.xlsx", index=False)
products.to_excel("cleaned_data/products_cleaned.xlsx", index=False)
reviews.to_excel("cleaned_data/reviews_cleaned.xlsx", index=False)
sellers.to_excel("cleaned_data/sellers_cleaned.xlsx", index=False)
geolocation.to_excel("cleaned_data/geolocation_cleaned.xlsx", index=False)